name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: 'ubuntu-20.04'
            env:
              CC: gcc
              CXX: g++
              FC: gfortran
          - os: 'ubuntu-20.04'
            env:
              CC: clang
              CXX: clang++
              FC: gfortran
          #- os: 'macos-latest'
          #  env:
          #    CC: gcc
          #    CXX: g++
          #    FC: gfortran-10
          #- os: 'macos-latest'
          #  env:
          #    CC: clang
          #    CXX: clang++
          #    FC: gfortran-10

    runs-on: ${{ matrix.os }}
    env: ${{ matrix.env }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies (Linux)
        run: |
          sudo apt-get install gfortran libopenblas-dev libhdf5-openmpi-dev libptscotch-dev trilinos-all-dev libslicot-dev
        if: matrix.os == 'ubuntu-20.04'

      - name: Install dependencies (MacOS)
        run: |
          brew tap nlesc/nlesc
          brew install nlesc/nlesc/trilinos nlesc/nlesc/slicot
        if: matrix.os == 'macos-latest'

      - name: Checkout RAILS
        uses: actions/checkout@v2
        with:
          repository: Sbte/RAILS
          path: RAILS

      - name: Install RAILS
        run: |
          cd RAILS
          mkdir build
          cd build
          cmake ..
          make -j
          make install
      
      - name: Checkout JDQZPP
        uses: actions/checkout@v2
        with:
          repository: erik808/jdqzpp
          path: JDQZPP

      - name: Install JDQZPP
        run: |
          cd JDQZPP
          mkdir build
          cd build
          cmake ..
          make -j
          make install
          
      - name: Build I-EMIC
        run: |
          mkdir build
          cd build
          cmake ..
          make -j
      
      - name: Test I-EMIC
        run: |
          cd build
          make check
